knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        # On utilise ton template personnalisé (celui qui est dans templates/bundles/...)
        pagination: 'bundles/KnpPaginatorBundle/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        
        # FIX DE L'ERREUR : On repasse sur le lien de tri standard
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
