# framework:
#     default_locale: fr
#     translator:
#         default_path: '%kernel.project_dir%/translations'
#         fallbacks:
#             - fr
#         enabled_locales:
#             - fr
#             - en
#             - ar


framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr