parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AiTransportService:
        arguments:
            $apiKey: '%env(ANTHROPIC_API_KEY)%'

    App\Service\PaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'

    App\Service\ContactService:
        arguments:
            $adminEmail: '%env(ADMIN_EMAIL)%'
    App\Service\PhotoService:
        arguments:
            $unsplashAccessKey: '%env(UNSPLASH_ACCESS_KEY)%'

    App\Service\FlightService:
        arguments:
            $aviationStackApiKey: '%env(AVIATIONSTACK_API_KEY)%'

    App\Service\BoardingPassService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $adminEmail: '%env(ADMIN_EMAIL)%'
            $baseUrl: 'http://localhost:8000'
